#!/bin/bash

MAGITO_HOME=$(dirname "$(readlink "$0")")
REPO=$(basename "`pwd`")

case "$(uname -s)" in
    Darwin)
        EMACS=/Applications/Emacs.app/Contents/MacOS/Emacs
        ;;
    *)
        echo 'Unsupported OS'
        exit 2
        ;;
esac

${EMACS} --name="magito: $REPO" -q --load $MAGITO_HOME/init.el
